# Generated by Django 5.1.4 on 2025-04-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="tweet_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="tweet_text",
            field=models.TextField(null=True),
        ),
    ]
