# Generated by Django 5.1.4 on 2025-04-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_feedback_tweet_date_alter_feedback_tweet_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="author_username",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="sentiment",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="tweet_date",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="tweet_id",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="tweet_text",
        ),
        migrations.AddField(
            model_name="feedback",
            name="analyzed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feedback",
            name="feedback_data",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
